### ISSUE TITLE
拨号连接打开winray无法联网wifi可以

### ISSUE THREAD

**Issue by 2235784443** [TheMRLL/winxray#1]

**Comment by TheMRLL** [comment]
请使用工具清理DNS缓存。

**Comment by 2235784443** [comment]
![20201227153348](https://user-images.githubusercontent.com/49609184/103165962-0817d180-4859-11eb-8706-c2c77be776a8.jpg)
我将自动配置脚本填上http://127.0.0.1:1083/proxy.pac?668127515并且勾选上才可以
每次打开都这样
