### ISSUE TITLE
提几点建议

### ISSUE THREAD

**Issue by iT0toro** [TheMRLL/winxray#17]
1.让渡除部分权益，找一个好的合作者帮助改进代码。
2.除了原代码外，切实增加一些其他功能。

**Comment by TheMRLL** [comment]
我想出一个英文版的。你有好的英文水平高的人推荐吗？

**Comment by iT0toro** [comment]
> 我想出一个英文版的。你有好的英文水平高的人推荐吗？

花钱找人翻译呗，英语专业大学生也花不了几百块。

**Comment by iT0toro** [comment]
> 我想出一个英文版的。你有好的英文水平高的人推荐吗？

花钱呗。英语专业的也用不了几百块。
